"""add message actor metadata

Revision ID: 0201b6e6ed19
Revises: f10b6e9244ea
Create Date: 2026-08-05 20:23:00.072230

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0201b6e6ed19'
down_revision: Union[str, None] = 'f10b6e9244ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.alter_column('messages', 'role',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('messages', 'agent_id')
    # ### end Alembic commands ###

