"""update chat database models

Revision ID: 20df859f8480
Revises: d7f30e5b1c42
Create Date: 2026-08-02 13:37:43.425008

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '20df859f8480'
down_revision: Union[str, None] = 'd7f30e5b1c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('model_config_version_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_documents_source_chunk_model_version'), 'documents', type_='unique')
    op.create_index('documents_bot_active_model_config_version_idx', 'documents', ['bot_id', 'is_active', 'model_config_version_id'], unique=False)
    op.create_index('documents_source_idx', 'documents', ['source_id'], unique=False)
    op.create_unique_constraint('uq_documents_source_chunk_config_version', 'documents', ['source_id', 'model_config_version_id', 'chunk_index'])
    op.drop_column('documents', 'embedding_version')
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'embedding_provider')
    op.drop_column('documents', 'chunk_overlap')
    op.drop_column('documents', 'chunk_size')
    op.add_column('messages', sa.Column('model_config_version_id', sa.Uuid(), nullable=True))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.create_index('messages_conversation_created_at_idx', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.add_column('model_config_versions', sa.Column('version_number', sa.Integer(), nullable=False))
    op.add_column('model_config_versions', sa.Column('embedding_provider', sa.Text(), server_default=sa.text("'openai'"), nullable=False))
    op.add_column('model_config_versions', sa.Column('embedding_version', sa.Text(), nullable=True))
    op.add_column('model_config_versions', sa.Column('embedding_dimension', sa.Integer(), server_default=sa.text('1536'), nullable=False))
    op.add_column('model_config_versions', sa.Column('llm_provider', sa.Text(), nullable=False))
    op.add_column('model_config_versions', sa.Column('reranker_provider', sa.Text(), nullable=True))
    op.add_column('model_config_versions', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('model_config_versions', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('model_config_versions', 'bot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('model_config_versions', 'embedding_model',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('model_config_versions', 'llm_model',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('model_config_versions', 'retrieval_k',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_config_versions', 'similarity_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('model_config_versions', 'chunk_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_config_versions', 'chunk_overlap',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_config_versions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('model_config_version_bot_version_key', 'model_config_versions', ['bot_id', 'version_number'])
    op.create_index('model_config_versions_created_at_idx', 'model_config_versions', ['bot_id', 'created_at'], unique=False)
    op.create_index('model_config_versions_one_active_per_bot_idx', 'model_config_versions', ['bot_id'], unique=True, postgresql_where=sa.text('active = true'))
    op.add_column('retrieval_logs', sa.Column('model_config_version_id', sa.Uuid(), nullable=True))
    op.alter_column('retrieval_logs', 'organization_id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('retrieval_logs_bot_created_at_idx', 'retrieval_logs', ['bot_id', 'created_at'], unique=False)
    op.create_index('retrieval_logs_model_config_version_idx', 'retrieval_logs', ['model_config_version_id'], unique=False)
    op.add_column('training_jobs', sa.Column('model_config_version_id', sa.Uuid(), nullable=False))
    op.create_index('training_jobs_bot_status_idx', 'training_jobs', ['bot_id', 'status'], unique=False)
    op.create_index('training_jobs_model_config_version_idx', 'training_jobs', ['model_config_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('training_jobs_model_config_version_idx', table_name='training_jobs')
    op.drop_index('training_jobs_bot_status_idx', table_name='training_jobs')
    op.drop_column('training_jobs', 'model_config_version_id')
    op.drop_index('retrieval_logs_model_config_version_idx', table_name='retrieval_logs')
    op.drop_index('retrieval_logs_bot_created_at_idx', table_name='retrieval_logs')
    op.alter_column('retrieval_logs', 'organization_id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('retrieval_logs', 'model_config_version_id')
    op.drop_index('model_config_versions_one_active_per_bot_idx', table_name='model_config_versions', postgresql_where=sa.text('active = true'))
    op.drop_index('model_config_versions_created_at_idx', table_name='model_config_versions')
    op.drop_constraint('model_config_version_bot_version_key', 'model_config_versions', type_='unique')
    op.alter_column('model_config_versions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('model_config_versions', 'chunk_overlap',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('model_config_versions', 'chunk_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('model_config_versions', 'similarity_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('model_config_versions', 'retrieval_k',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('model_config_versions', 'llm_model',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model_config_versions', 'embedding_model',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model_config_versions', 'bot_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('model_config_versions', 'activated_at')
    op.drop_column('model_config_versions', 'created_by_user_id')
    op.drop_column('model_config_versions', 'reranker_provider')
    op.drop_column('model_config_versions', 'llm_provider')
    op.drop_column('model_config_versions', 'embedding_dimension')
    op.drop_column('model_config_versions', 'embedding_version')
    op.drop_column('model_config_versions', 'embedding_provider')
    op.drop_column('model_config_versions', 'version_number')
    op.drop_index('messages_conversation_created_at_idx', table_name='messages')
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('messages', 'model_config_version_id')
    op.add_column('documents', sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('chunk_overlap', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('embedding_provider', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('embedding_model', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('embedding_version', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_documents_source_chunk_config_version', 'documents', type_='unique')
    op.drop_index('documents_source_idx', table_name='documents')
    op.drop_index('documents_bot_active_model_config_version_idx', table_name='documents')
    op.create_unique_constraint(op.f('uq_documents_source_chunk_model_version'), 'documents', ['source_id', 'chunk_index', 'embedding_model', 'embedding_version'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'model_config_version_id')
    # ### end Alembic commands ###

