"""sync chat database models

Revision ID: 5237389a3f48
Revises: a1c3e8f29b04
Create Date: 2026-09-08 14:02:49.937754

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5237389a3f48"
down_revision: str | None = "a1c3e8f29b04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.alter_column(
        "retrieval_logs",
        "reranker_used",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "retrieval_logs",
        "reranker_used",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_column("documents", "metadata_json")
    # ### end Alembic commands ###
