"""init chat db

Revision ID: 8aed880f05ee
Revises: 
Create Date: 2026-02-06 15:49:24.706504

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8aed880f05ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make this migration resilient if it was partially applied previously.
    op.execute(
        sa.text("ALTER TABLE documents ADD COLUMN IF NOT EXISTS embedding_provider text")
    )

    # NOTE: Legacy schemas used BIGINT bot_id. There is no safe cast BIGINT -> UUID.
    # We only perform the change if the tables are empty; otherwise we abort.
    op.execute(
        sa.text(
            r"""
            DO $$
            DECLARE
              documents_bot_type text;
              jobs_bot_type text;
            BEGIN
              SELECT data_type INTO documents_bot_type
              FROM information_schema.columns
              WHERE table_schema = current_schema()
                AND table_name = 'documents'
                AND column_name = 'bot_id';

              SELECT data_type INTO jobs_bot_type
              FROM information_schema.columns
              WHERE table_schema = current_schema()
                AND table_name = 'training_jobs'
                AND column_name = 'bot_id';

              -- documents.bot_id: BIGINT -> UUID (only if empty)
              IF documents_bot_type = 'bigint' THEN
                IF EXISTS (SELECT 1 FROM documents LIMIT 1) THEN
                  RAISE EXCEPTION 'Cannot migrate documents.bot_id BIGINT->UUID: table is not empty';
                END IF;
                ALTER TABLE documents DROP COLUMN bot_id;
                ALTER TABLE documents ADD COLUMN bot_id uuid NOT NULL;
              END IF;

              -- training_jobs.bot_id: BIGINT -> UUID (only if empty)
              IF jobs_bot_type = 'bigint' THEN
                IF EXISTS (SELECT 1 FROM training_jobs LIMIT 1) THEN
                  RAISE EXCEPTION 'Cannot migrate training_jobs.bot_id BIGINT->UUID: table is not empty';
                END IF;
                ALTER TABLE training_jobs DROP COLUMN bot_id;
                ALTER TABLE training_jobs ADD COLUMN bot_id uuid NOT NULL;
              END IF;
            END$$;
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverting UUID->BIGINT is not supported automatically.
    op.execute(
        sa.text(
            "RAISE EXCEPTION 'Downgrade not supported for bot_id UUID->BIGINT conversion';"
        )
    )
    op.drop_column('documents', 'embedding_provider')
    # ### end Alembic commands ###

