"""add_unique_constraints to documents and embeddings

Revision ID: b0c5f620e87c
Revises: 8aed880f05ee
Create Date: 2026-02-06 17:52:43.090272

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b0c5f620e87c'
down_revision: Union[str, None] = '8aed880f05ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_documents_source_chunk_model_version', 'documents', ['source_id', 'chunk_index', 'embedding_model', 'embedding_version'])
    op.create_unique_constraint('uq_embeddings_document_id', 'embeddings', ['document_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_embeddings_document_id', 'embeddings', type_='unique')
    op.drop_constraint('uq_documents_source_chunk_model_version', 'documents', type_='unique')
    # ### end Alembic commands ###

