"""split model configurations

Revision ID: f10b6e9244ea
Revises: 20df859f8480
Create Date: 2026-08-04 14:31:43.704479

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f10b6e9244ea'
down_revision: Union[str, None] = '20df859f8480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('retrieval_k', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Double(precision=53), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("state IN ('draft', 'training', 'active', 'failed', 'deprecated')", name='bot_config_state_valid'),
    sa.CheckConstraint('retrieval_k > 0', name='bot_config_retrieval_k_positive'),
    sa.CheckConstraint('similarity_threshold >= 0.0 and similarity_threshold <= 1.0', name='bot_config_similarity_threshold_range'),
    sa.PrimaryKeyConstraint('id', name='bot_config_pkey'),
    )
    op.create_index('bot_configurations_one_active_per_bot_idx', 'bot_configurations', ['bot_id'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_table('embedding_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('dimension', sa.Integer(), server_default=sa.text('1536'), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("state IN ('draft', 'training', 'active', 'failed', 'deprecated')", name='embedding_config_state_valid'),
    sa.CheckConstraint('chunk_overlap >= 0 and chunk_overlap < chunk_size', name='embedding_config_chunk_overlap_range'),
    sa.CheckConstraint('chunk_size > 0', name='embedding_config_chunk_size_positive'),
    sa.CheckConstraint('dimension > 0', name='embedding_config_dimension_positive'),
    sa.PrimaryKeyConstraint('id', name='embedding_config_pkey'),
    )
    op.create_index('embedding_configurations_one_active_per_bot_idx', 'embedding_configurations', ['bot_id'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.drop_index(op.f('model_config_versions_created_at_idx'), table_name='model_config_versions')
    op.drop_index(op.f('model_config_versions_one_active_per_bot_idx'), table_name='model_config_versions', postgresql_where='(active = true)')
    op.drop_table('model_config_versions')
    op.add_column('documents', sa.Column('embedding_configuration_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('documents_bot_active_model_config_version_idx'), table_name='documents')
    op.drop_constraint(op.f('uq_documents_source_chunk_config_version'), 'documents', type_='unique')
    op.create_unique_constraint('uq_documents_source_chunk_config_version', 'documents', ['source_id', 'embedding_configuration_id', 'chunk_index'])
    op.create_index('documents_bot_active_embedding_configuration_idx', 'documents', ['bot_id', 'is_active', 'embedding_configuration_id'], unique=False)
    op.drop_column('documents', 'model_config_version_id')
    op.add_column('messages', sa.Column('embedding_configuration_id', sa.Uuid(), nullable=True))
    op.add_column('messages', sa.Column('bot_configuration_id', sa.Uuid(), nullable=True))
    op.drop_column('messages', 'model_config_version_id')
    op.add_column('retrieval_logs', sa.Column('embedding_configuration_id', sa.Uuid(), nullable=True))
    op.add_column('retrieval_logs', sa.Column('llm_configuration_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('retrieval_logs_model_config_version_idx'), table_name='retrieval_logs')
    op.create_index('retrieval_logs_configuration_id_idx', 'retrieval_logs', ['embedding_configuration_id', 'llm_configuration_id'], unique=False)
    op.drop_column('retrieval_logs', 'model_config_version_id')
    op.add_column('training_jobs', sa.Column('embedding_configuration_id', sa.Uuid(), nullable=False))
    op.add_column('training_jobs', sa.Column('bot_configuration_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('training_jobs_model_config_version_idx'), table_name='training_jobs')
    op.create_index('training_jobs_embedding_configuration_id_idx', 'training_jobs', ['embedding_configuration_id'], unique=False)
    op.drop_column('training_jobs', 'model_config_version_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_jobs', sa.Column('model_config_version_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('training_jobs_embedding_configuration_id_idx', table_name='training_jobs')
    op.create_index(op.f('training_jobs_model_config_version_idx'), 'training_jobs', ['model_config_version_id'], unique=False)
    op.drop_column('training_jobs', 'bot_configuration_id')
    op.drop_column('training_jobs', 'embedding_configuration_id')
    op.add_column('retrieval_logs', sa.Column('model_config_version_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index('retrieval_logs_configuration_id_idx', table_name='retrieval_logs')
    op.create_index(op.f('retrieval_logs_model_config_version_idx'), 'retrieval_logs', ['model_config_version_id'], unique=False)
    op.drop_column('retrieval_logs', 'llm_configuration_id')
    op.drop_column('retrieval_logs', 'embedding_configuration_id')
    op.add_column('messages', sa.Column('model_config_version_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'bot_configuration_id')
    op.drop_column('messages', 'embedding_configuration_id')
    op.add_column('documents', sa.Column('model_config_version_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('documents_bot_active_embedding_configuration_idx', table_name='documents')
    op.drop_constraint('uq_documents_source_chunk_config_version', 'documents', type_='unique')
    op.create_unique_constraint(op.f('uq_documents_source_chunk_config_version'), 'documents', ['source_id', 'model_config_version_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('documents_bot_active_model_config_version_idx'), 'documents', ['bot_id', 'is_active', 'model_config_version_id'], unique=False)
    op.drop_column('documents', 'embedding_configuration_id')
    op.create_table('model_config_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding_model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('llm_model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reranker_model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retrieval_k', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('similarity_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_overlap', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding_provider', sa.TEXT(), server_default=sa.text("'openai'::text"), autoincrement=False, nullable=False),
    sa.Column('embedding_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding_dimension', sa.INTEGER(), server_default=sa.text('1536'), autoincrement=False, nullable=False),
    sa.Column('llm_provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reranker_provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('model_config_versions_pkey')),
    sa.UniqueConstraint('bot_id', 'version_number', name=op.f('model_config_version_bot_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('model_config_versions_one_active_per_bot_idx'), 'model_config_versions', ['bot_id'], unique=True, postgresql_where='(active = true)')
    op.create_index(op.f('model_config_versions_created_at_idx'), 'model_config_versions', ['bot_id', 'created_at'], unique=False)
    op.drop_index('embedding_configurations_one_active_per_bot_idx', table_name='embedding_configurations', postgresql_where=sa.text("state = 'active'"))
    op.drop_table('embedding_configurations')
    op.drop_index('bot_configurations_one_active_per_bot_idx', table_name='bot_configurations', postgresql_where=sa.text("state = 'active'"))
    op.drop_table('bot_configurations')
    # ### end Alembic commands ###

