"""add deleted_at fields to embeddings and documents table

Revision ID: fc1514028346
Revises: b0c5f620e87c
Create Date: 2026-02-11 04:31:04.200049

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc1514028346"
down_revision: str | None = "b0c5f620e87c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "embeddings", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embeddings", "deleted_at")
    op.drop_column("documents", "deleted_at")
    # ### end Alembic commands ###
